version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - .docker/.data/.postgresql/13/data:/var/lib/postgresql/data
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/home/app
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE="sgm-development"
      - DB_HOST=postgres
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - postgres
