default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  pool: 5

development:
  <<: *default
  user: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  database: ENV['DB_DATABASE']


test:
  <<: *default
  database: ENV['NAME_DATABASE_TEST']
