default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  pool: 5

development:
  <<: *default
  database: sgm_development


test:
  <<: *default
  database: sgm_test
